---
title: Diagramma dei package tra mapClient e mapServer (GUI)
---
flowchart TD

    subgraph mapClient["mapClient"]
        direction TB
        Main["Main"]
        Controller["Controller"]
        Load_From_Controller["Load_From_Controller"]
        RtClient["RtClient"]
        ServerException["ServerException"]
        Main ~~~ Controller ~~~ Load_From_Controller ~~~ RtClient ~~~ ServerException
    end

    subgraph mapServer["mapServer"]
        direction TB
        MainTest["MainTest"]
        MultiServer["MultiServer"]
        ServerOneClient["ServerOneClient"]
        Data["Data"]
        RegressionTree["RegressionTree"]
        MainTest ~~~ MultiServer ~~~ ServerOneClient ~~~ Data ~~~ RegressionTree
    end

    mapClient -.->|Socket TCP| mapServer
