---
title: Diagramma dei package di mapClient/src
---
flowchart TD

subgraph src["src"]

    subgraph mapClientPkg["mapClient"]
        Command["Command"]
        MainTest["MainTest"]
        MapBot["MapBot"]
        ServerConnection["ServerConnection"]
        Command ~~~ MainTest ~~~ MapBot ~~~ ServerConnection
    end

end
